# Generated by Django 6.1 on 2026-08-21 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaxonomyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopify_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('gid', models.CharField(blank=True, db_index=True, max_length=200)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('full_path', models.TextField(db_index=True)),
                ('level', models.IntegerField(db_index=True, default=1)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='taxonomy.taxonomycategory')),
            ],
            options={
                'verbose_name_plural': 'Taxonomy Categories',
                'ordering': ['full_path'],
            },
        ),
        migrations.CreateModel(
            name='TaxonomyAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid', models.CharField(blank=True, db_index=True, max_length=200)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('value_type', models.CharField(blank=True, default='string', max_length=100)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='taxonomy.taxonomycategory')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='taxonomycategory',
            index=models.Index(fields=['shopify_id'], name='taxonomy_ta_shopify_01c1a5_idx'),
        ),
        migrations.AddIndex(
            model_name='taxonomycategory',
            index=models.Index(fields=['parent'], name='taxonomy_ta_parent__7393a3_idx'),
        ),
        migrations.AddIndex(
            model_name='taxonomycategory',
            index=models.Index(fields=['name'], name='taxonomy_ta_name_06666d_idx'),
        ),
        migrations.AddIndex(
            model_name='taxonomycategory',
            index=models.Index(fields=['level'], name='taxonomy_ta_level_c9712f_idx'),
        ),
        migrations.AddIndex(
            model_name='taxonomyattribute',
            index=models.Index(fields=['name'], name='taxonomy_ta_name_00d3c5_idx'),
        ),
    ]
