# Generated by Django 6.1 on 2026-09-01 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxonomyAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid', models.CharField(db_index=True, max_length=200)),
                ('value', models.CharField(db_index=True, max_length=500)),
                ('normalized_value', models.CharField(db_index=True, max_length=500)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='taxonomy.taxonomyattribute')),
            ],
            options={
                'ordering': ['value'],
                'indexes': [models.Index(fields=['attribute', 'normalized_value'], name='taxonomy_ta_attribu_910ce6_idx'), models.Index(fields=['gid'], name='taxonomy_ta_gid_824f09_idx')],
                'constraints': [models.UniqueConstraint(fields=('attribute', 'gid'), name='unique_taxonomy_attribute_value_gid'), models.UniqueConstraint(fields=('attribute', 'normalized_value'), name='unique_taxonomy_attribute_value_normalized')],
            },
        ),
    ]
