# Generated by Django 6.1 on 2026-08-21 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('PAUSED', 'Paused')], db_index=True, default='PENDING', max_length=20)),
                ('total_products', models.IntegerField(default=0)),
                ('processed_products', models.IntegerField(default=0)),
                ('successful_products', models.IntegerField(default=0)),
                ('failed_products', models.IntegerField(default=0)),
                ('manual_review_products', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClassificationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence_score', models.FloatField(db_index=True, default=0.0)),
                ('status', models.CharField(default='COMPLETED', max_length=50)),
                ('image_used', models.BooleanField(default=False)),
                ('model_used', models.CharField(default='Demo Mode (Rule + TF-IDF)', max_length=100)),
                ('explanation', models.TextField(blank=True)),
                ('requires_review', models.BooleanField(db_index=True, default=False)),
                ('user_approved', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manual_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_classifications', to='taxonomy.taxonomycategory')),
                ('selected_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classifications', to='taxonomy.taxonomycategory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClassificationAlternative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence_score', models.FloatField()),
                ('rank', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxonomy.taxonomycategory')),
                ('classification_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternatives', to='products.classificationresult')),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_number', models.CharField(db_index=True, max_length=100)),
                ('model_number', models.CharField(blank=True, db_index=True, max_length=100)),
                ('title', models.CharField(db_index=True, max_length=500)),
                ('description', models.TextField(blank=True)),
                ('bullets', models.TextField(blank=True)),
                ('product_category', models.CharField(blank=True, db_index=True, max_length=255)),
                ('product_subcategory', models.CharField(blank=True, db_index=True, max_length=255)),
                ('collection_name', models.CharField(blank=True, max_length=255)),
                ('brand', models.CharField(blank=True, max_length=255)),
                ('color', models.CharField(blank=True, max_length=255)),
                ('materials', models.CharField(blank=True, max_length=500)),
                ('dimensions', models.CharField(blank=True, max_length=500)),
                ('set_includes', models.TextField(blank=True)),
                ('assembly_required', models.CharField(blank=True, max_length=50)),
                ('is_set', models.CharField(blank=True, max_length=50)),
                ('stackable', models.CharField(blank=True, max_length=50)),
                ('country_of_origin', models.CharField(blank=True, max_length=255)),
                ('product_url', models.CharField(blank=True, max_length=1000)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('content_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('processing_status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('RETRY', 'Retry'), ('MANUAL_REVIEW', 'Manual Review')], db_index=True, default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.processingjob')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='classificationresult',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='classification', to='products.product'),
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_name', models.CharField(max_length=255)),
                ('attribute_value', models.CharField(max_length=500)),
                ('confidence_score', models.FloatField(default=1.0)),
                ('source', models.CharField(default='Extracted', max_length=100)),
                ('classification_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='products.classificationresult')),
            ],
            options={
                'ordering': ['attribute_name'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=1000)),
                ('local_path', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('http_status', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('processed', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['product_number'], name='products_pr_product_1e41d2_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['model_number'], name='products_pr_model_n_80d291_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['processing_status'], name='products_pr_process_7d7449_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['content_hash'], name='products_pr_content_246bb6_idx'),
        ),
        migrations.AddIndex(
            model_name='classificationresult',
            index=models.Index(fields=['requires_review'], name='products_cl_require_f0ae11_idx'),
        ),
        migrations.AddIndex(
            model_name='classificationresult',
            index=models.Index(fields=['confidence_score'], name='products_cl_confide_137720_idx'),
        ),
        migrations.AddIndex(
            model_name='classificationresult',
            index=models.Index(fields=['user_approved'], name='products_cl_user_ap_591967_idx'),
        ),
    ]
