# Generated by Django 6.1 on 2026-09-01 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattribute',
            name='shopify_attribute_gid',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='shopify_value_gid',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AddIndex(
            model_name='productattribute',
            index=models.Index(fields=['shopify_attribute_gid'], name='products_pr_shopify_4e211f_idx'),
        ),
        migrations.AddIndex(
            model_name='productattribute',
            index=models.Index(fields=['shopify_value_gid'], name='products_pr_shopify_95ef1a_idx'),
        ),
    ]
